@startuml
'https://plantuml.com/sequence-diagram

class Solution42 {
    'behaviors
    +readLine(fileName, thisLine): String
    +addToArrayList(String): void
    +printHashmapIndexToFile(String): String
    +printFullFile(ArrayList<String>): String


    'attributes
    -fileName: String
    -nameCount: int

}

class Person {
    -firstName: String
    -lastName: String

    +Person(String name)
    +toString(Person person): String
    +compareTo(): int
}

Solution42 --|> Person

@enduml