@startuml

class Solution46 {

    -frequency: Hashmap<String, int>
    -textParsed: ArrayList<String>

    +main(String[]): void
    +readFromFile(String): void
    +generateTable(Hashmap<String, int>): String

}

@enduml